services:
  - type: web
    name: gerador-de-kpi
    runtime: python
    pythonVersion: "3.11"
    buildCommand: pip install --prefer-binary -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
